### ISSUE TITLE
来自d版带着爱，哪个电视软件比较推荐

### ISSUE THREAD

**Issue by jfsd2000** [openwrt166/firetv#1]
尤其是海外电视，现在很多电视源都有广告，真是不给力。

**Comment by jfsd2000** [comment]
忘记谢谢up主了。

**Comment by openwrt166** [comment]
播放软件就用Perfect Player最好，主要在于直播源能用才行。如果要看海外的，FireTV上最多了，不过都是要订阅收费的。NetFlix,HBO,Disney+......要多少有多少。

要看免费的，就用Perfect Player,然后找能用的直播源。下面两个最全，但是需要自己慢慢测试。可以在电脑上先用PotPlayer试过能放，再加进盒子。
https://github.com/iptv-org/iptv

https://github.com/biancangming/wtv/wiki/%E6%9C%80%E6%96%B0IPTV%E7%9B%B4%E6%92%AD%E6%BA%90m3u8%E4%B8%8B%E8%BD%BD%EF%BC%8C%E7%94%B5%E8%A7%86%E7%9B%B4%E6%92%AD%E7%BD%91%E7%AB%99%E6%8E%A8%E8%8D%90

直播源的管理可以看我在D板的帖子.

**Comment by jfsd2000** [comment]
> 播放软件就用Perfect Player最好，主要在于直播源能用才行。如果要看海外的，FireTV上最多了，不过都是要订阅收费的。NetFlix,HBO,Disney+......要多少有多少。
> 
> 要看免费的，就用Perfect Player,然后找能用的直播源。下面两个最全，但是需要自己慢慢测试。可以在电脑上先用PotPlayer试过能放，再加进盒子。
> https://github.com/iptv-org/iptv
> 
> https://github.com/biancangming/wtv/wiki/%E6%9C%80%E6%96%B0IPTV%E7%9B%B4%E6%92%AD%E6%BA%90m3u8%E4%B8%8B%E8%BD%BD%EF%BC%8C%E7%94%B5%E8%A7%86%E7%9B%B4%E6%92%AD%E7%BD%91%E7%AB%99%E6%8E%A8%E8%8D%90
> 
> 直播源的管理可以看我在D板的帖子.

太给力了，再请问atv0.13升级0.15是不是只要删掉0.13再安装0.15

**Comment by openwrt166** [comment]
是的
